en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} Sequoia Ploeg. All Rights Reserved."
  title: "PG03"
  params:
    description: "Precinct website for PG03."
    ### accessibility ###
    # accessibility:
    #   skip_text: "Skip to content"
    #   help_text: "Accessibility Statement"
    #   help_url: "/newsletter/"
    ### calls to action ###
    main_cta:
      text: "Email Updates"
      link: "/newsletter/"
    footer_cta:
      text: "Email Updates"
      link: "/newsletter/"
    # github_edit: "Edit this page on GitHub"
  menu:
    main:
    - identifier: "races"
      name: "Races"
      url: "/races/"
      weight: 1
    - identifier: "race-senator-21"
      name: "State Senator District 21"
      url: "/races/state-senator-21/"
      weight: 1
      parent: "races"
    - identifier: "race-house-55"
      name: "State House District 55"
      url: "/races/state-house-55/"
      weight: 2
      parent: "races"
    - identifier: "race-commissioner-a"
      name: "County Commissioner Seat A"
      url: "/races/county-commissioner-a/"
      weight: 3
      parent: "races"
    - identifier: "race-commissioner-b"
      name: "County Commissioner Seat B"
      url: "/races/county-commissioner-b/"
      weight: 4
      parent: "races"
    - identifier: "race-assessor"
      name: "County Assessor"
      url: "/races/county-assessor/"
      weight: 5
      parent: "races"
    - identifier: "race-attorney"
      name: "County Attorney"
      url: "/races/county-attorney/"
      weight: 6
      parent: "races"
    - identifier: "race-auditor"
      name: "County Auditor"
      url: "/races/county-auditor/"
      weight: 7
      parent: "races"
    - identifier: "race-clerk"
      name: "County Clerk"
      url: "/races/county-clerk/"
      weight: 8
      parent: "races"
    - identifier: "race-sheriff"
      name: "County Sheriff"
      url: "/races/county-sheriff/"
      weight: 9
      parent: "races"
    - identifier: "race-us-house-4"
      name: "US House District 4"
      url: "/races/us-house-4/"
      weight: 10
      parent: "races"
    - identifier: "race-school-board-11"
      name: "State School Board District 11"
      url: "/races/state-school-board-11/"
      weight: 11
      parent: "races"
    - identifier: "issues"
      name: "Issues"
      url: "/issues/"
      weight: 2
    - identifier: "issue-infrastructure"
      name: "Infrastructure"
      url: "/issues/infrastructure/"
      weight: 1
      parent: "issues"
    - identifier: "issue-immigration"
      name: "Immigration"
      url: "/issues/immigration/"
      weight: 2
      parent: "issues"
    - identifier: "issue-law-enforcement"
      name: "Law Enforcement"
      url: "/issues/law-enforcement/"
      weight: 3
      parent: "issues"
    - identifier: "issue-elections"
      name: "Elections"
      url: "/issues/elections/"
      weight: 4
      parent: "issues"
    - identifier: "news"
      name: "News"
      url: "/news/"
      weight: 3
    - identifier: "news-all"
      name: "All News"
      url: "/news/"
      weight: 1
      parent: "news"
    - identifier: "news-county"
      name: "County News"
      url: "/categories/county/"
      weight: 2
      parent: "news"
    - identifier: "news-state"
      name: "State News"
      url: "/categories/state/"
      weight: 3
      parent: "news"
    - identifier: "straw-poll"
      name: "Straw Poll"
      url: "/straw-poll/"
      weight: 4